# Generated by Django 3.1.3 on 2022-01-08 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ValuationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vapp',
            name='customeuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ValuationApp.customuser'),
        ),
    ]
