# Generated by Django 3.1.3 on 2022-01-10 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ValuationApp', '0002_vapp_customeuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='issue_id',
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='site_visit_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='vapp',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='vapp',
            name='customeuser',
        ),
        migrations.AddField(
            model_name='vapp',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
