# Generated by Django 3.2.11 on 2022-01-13 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ValuationApp', '0003_auto_20220110_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banksubmission_comments', models.CharField(blank=True, max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('last_update_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Last_Update_Timestamp_Timestamp')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldreport_location', models.CharField(blank=True, max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('last_update_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Last_Update_Timestamp_Timestamp')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoleRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created_Timestamp')),
                ('last_update_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Last_Update_Timestamp_Timestamp')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.RenameField(
            model_name='vapp',
            old_name='property_name',
            new_name='case_code',
        ),
        migrations.RenameField(
            model_name='vapp',
            old_name='owner_phone',
            new_name='owner_phone1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='created',
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='site_visit_date',
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='site_visit_location',
        ),
        migrations.RemoveField(
            model_name='vapp',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='vapp',
            name='property_address',
        ),
        migrations.RemoveField(
            model_name='vapp',
            name='property_status',
        ),
        migrations.RemoveField(
            model_name='vapp',
            name='purpose',
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created_Timestamp'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_update_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Last_Update_Timestamp_Timestamp'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='terms',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='last_update_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Last_Update_Timestamp_Timestamp'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vapp',
            name='case_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vapp',
            name='case_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vapp',
            name='case_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vapp',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vapp',
            name='google_map',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vapp',
            name='landmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vapp',
            name='last_update_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Last_Update_Timestamp_Timestamp'),
        ),
        migrations.AddField(
            model_name='vapp',
            name='loan_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vapp',
            name='owner_phone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vapp',
            name='owner_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='vapp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ValuationApp.vapp'),
        ),
        migrations.AddField(
            model_name='banksubmission',
            name='vapp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ValuationApp.vapp'),
        ),
        migrations.AddField(
            model_name='issue',
            name='banksubmission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ValuationApp.banksubmission'),
        ),
    ]
