# Generated by Django 3.2.11 on 2022-01-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValuationApp', '0004_auto_20220113_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelsheetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_case_no', models.CharField(blank=True, max_length=2000, null=True)),
                ('sheet_case_code', models.CharField(blank=True, max_length=2000, null=True)),
                ('sheet_file_no', models.CharField(blank=True, max_length=2000, null=True)),
                ('sheet_case_id', models.CharField(blank=True, max_length=2000, null=True)),
                ('sheet_case_status', models.CharField(blank=True, max_length=2000, null=True)),
                ('sheet_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('sheet_address', models.CharField(blank=True, max_length=2000, null=True)),
                ('sheet_city', models.CharField(blank=True, max_length=2000, null=True)),
                ('sheet_phone1', models.CharField(blank=True, max_length=2000, null=True)),
                ('sheet_phone2', models.CharField(blank=True, max_length=2000, null=True)),
                ('sheet_landmark', models.CharField(blank=True, max_length=2000, null=True)),
                ('sheet_loan_type', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
