# Generated by Django 3.2.11 on 2022-01-13 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ValuationApp', '0005_excelsheetdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='banksubmission',
        ),
        migrations.AlterModelTable(
            name='excelsheetdata',
            table='ExcelsheetData',
        ),
    ]
