# Generated by Django 3.2.11 on 2022-01-13 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ValuationApp', '0007_fieldreport_fieldreport_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='banksubmission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ValuationApp.banksubmission'),
        ),
    ]
