# Generated by Django 3.2.11 on 2022-01-13 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ValuationApp', '0008_issue_banksubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excelsheetdata',
            old_name='sheet_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='excelsheetdata',
            old_name='sheet_case_code',
            new_name='case_code',
        ),
        migrations.RenameField(
            model_name='excelsheetdata',
            old_name='sheet_case_id',
            new_name='case_id',
        ),
        migrations.RenameField(
            model_name='excelsheetdata',
            old_name='sheet_case_no',
            new_name='case_no',
        ),
        migrations.RenameField(
            model_name='excelsheetdata',
            old_name='sheet_case_status',
            new_name='case_status',
        ),
        migrations.RenameField(
            model_name='excelsheetdata',
            old_name='sheet_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='excelsheetdata',
            old_name='sheet_file_no',
            new_name='file_no',
        ),
        migrations.RenameField(
            model_name='excelsheetdata',
            old_name='sheet_landmark',
            new_name='landmark',
        ),
        migrations.RenameField(
            model_name='excelsheetdata',
            old_name='sheet_loan_type',
            new_name='loan_type',
        ),
        migrations.RenameField(
            model_name='excelsheetdata',
            old_name='sheet_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='excelsheetdata',
            old_name='sheet_phone1',
            new_name='phone1',
        ),
        migrations.RenameField(
            model_name='excelsheetdata',
            old_name='sheet_phone2',
            new_name='phone2',
        ),
    ]
