# Generated by Django 3.2.11 on 2022-01-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValuationApp', '0009_auto_20220113_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_address', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_city', models.CharField(blank=True, max_length=50, null=True)),
                ('Bank_state', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
