# Generated by Django 3.2.11 on 2022-01-14 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ValuationApp', '0010_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='banksubmission',
        ),
        migrations.AddField(
            model_name='customuser',
            name='roleref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ValuationApp.roleref'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ValuationApp.issue'),
        ),
        migrations.AddField(
            model_name='vapp',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ValuationApp.bank'),
        ),
        migrations.DeleteModel(
            name='BankSubmission',
        ),
    ]
