# Generated by Django 3.2.11 on 2022-01-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ValuationApp', '0011_auto_20220114_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
