# Generated by Django 3.2.11 on 2022-01-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValuationApp', '0013_auto_20220117_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='site_visit_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
