# Generated by Django 3.2.11 on 2022-01-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValuationApp', '0014_sitevisit_site_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreport',
            name='fieldreport_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
